name: test

on:
  push:
    branches:
      - main
      - feature-*
  workflow_dispatch:
jobs:
  if_merged: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo A PR was merged into the main branch.

  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x" # Use appropriate Node.js version here

      - name: Install dependencies
        run: npm ci

      - name: Format Code
        run: touch test.yaml 

      - name: Determine EAS Profile
        id: determine_profile
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_ENV

      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Auto-Applied Code Formatting
          # branch: ${{github.ref_name}}

      - name: Commit changes and push
        run: |
         git config --global user.email "actions@github.com"
         git config --global user.name "GitHub Actions"
         git add .
         git commit -m "Auto-Applied Code Formatting"
         git push origin ${{ env.BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}


      # - name: Run tests
      #   run: npm test

      - name: Run build
        run: npm run build --if-present

  docker-build:
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [if_merged]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sivatheja2013/github-notes-app
          tags: |
            type=ref,event=pr
            type=ref,ref=${{ github.ref }}
            type=sha,ref=${{ github.sha }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
