name: Slack Notification

on:
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, review_requested, review_request_removed, labeled, unlabeled, synchronize, ready_for_review, locked, unlocked, auto_merge, pull_request_review, pull_request_review_comment, labeled, unlabeled]
    branches:
    - main

jobs:
  get_githubrepo_name:
    runs-on: ubuntu-latest
    steps:
    - name: Set ENV variables
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
    - name: Use the custom ENV variable
      run: |
        echo $REPO_NAME
  
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"A pull request from ${{ github.event_name }}: ${{ github.event.pull_request.html_url }}\"}" ${{env.SLACK_WEBHOOK_URL}}
          # curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"A pull request was ${{ github.event_name }}: ${{ github.event.pull_request.html_url }}\"}" $SLACK_WEBHOOK_URL
        env:
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

        
