name: Slack Notification

on:
  push:
    branches:
        - feature-3
  pull_request:
    types: [opened, closed, reopened, edited, assigned, unassigned, review_requested, review_request_removed, synchronize, ready_for_review, locked, unlocked, auto_merge, pull_request_review, pull_request_review_comment, labeled, unlabeled]
    branches:
      - main

jobs:
  get_githubrepo_name:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
          echo "SAUCE_USERNAME=${{ Ssecrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ Ssecrets.SAUCE_ACCESS_KEY }} >> $GITHUB_ENV

          curl -u "$SAUCE_ACCESS_KEY:$SAUCE_ACCESS_KEY" --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' --form 'payload=@"/Users/runner/Library/Developer/Xcode/DerivedData/HealthcareFrontend-aexroozlhbtsbmhajvliippddzsc/Build/Products/Debug-iphonesimulator/HealthcareFrontend.zip"' --form 'name="HealthcareFrontend.zip"'
  
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV variables
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"A pull request from $REPO_NAME: ${{ github.event.pull_request.html_url }}\"}" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
