name: GitHub Leaks

on:
  push:
   branches:
     - main
     - feature-*
  pull_request:
    types: [opened, synchronize]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: gitleaks/gitleaks-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        
