name: print_name
 
on:
    workflow_dispatch:
    push:
      branches:
        - develop
        - main

jobs:
   print:
     timeout-minutes: 30
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
       - name: Determine env
         id: determine_env
         run: |
            PROFILE=$(echo $GITHUB_REF | cut -d'/' -f3)
            # Check if PROFILE is one of the valid values; otherwise, set it to 'develop'
            if [[ "$PROFILE" = feature_*_fastlane ]]; then
              PROFILE="develop"
            fi
            echo "PROFILE=${PROFILE}" >> $GITHUB_ENV

       - name: Validate env
         id: validate_env
         run: |
            if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
              echo "Invalid PROFILE value: ${{ env.PROFILE }} \n
              branch name shall be either develop/stage/test/main or feature_*_fastlane to trigger the mobile builds"
              exit 1
            fi
 
       - name: print env
         run: echo "${{ env.PROFILE }}"

       - name: Set environment variables based on branch
         run: |
             if [ "${{ github.ref }}" == "refs/heads/main" ]; then
               echo "KEY=${{ secrets.MAIN_KEY }}" >> test/.env
               echo "SECRET=${{ secrets.MAIN_SECRET }}" >> test/.env
             elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
               echo "KEY=${{ vars.DEVELOP_KEY }}" >> test/.env
               echo "SECRET=${{ secrets.DEVELOP_SECRET }}" >> test/.env
             elif [ "${{ github.ref }}" == "refs/heads/stage" ]; then
               echo "KEY=${{ secrets.MAIN_KEY }}" >> test/.env
               echo "SECRET=${{ secrets.MAIN_SECRET }}" >> test/.env
             elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
               echo "KEY=${{ secrets.MAIN_KEY }}" >> test/.env
               echo "SECRET=${{ secrets.MAIN_SECRET }}" >> test/.env
             elif [[ "${{ github.ref }}" == "refs/heads/feature_*_fastlane" ]]; then
               echo "KEY=${{ secrets.DEVELOP_KEY }}" >> test/.env
               echo "SECRET=${{ secrets.DEVELOP_SECRET }}" >> test/.env
             fi
       - name: Check .env file content
         run: |
          echo "Checking .env file contents"
          grep -E '^KEY=' test/.env
          grep -E '^SECRET=' .env
