name: print_name
 
on:
    workflow_dispatch:
    push:
      branches:
        - feature_*_fastlane

jobs:
   android:
     timeout-minutes: 30
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
       - name: Determine env
         id: determine_env
         run: |
            PROFILE=$(echo $GITHUB_REF | cut -d'/' -f3)
            # Check if PROFILE is one of the valid values; otherwise, set it to 'develop'
            if [[ "$PROFILE" = feature_*_fastlane ]]; then
              PROFILE="develop"
            fi
            echo "PROFILE=${PROFILE}" >> $GITHUB_ENV
 
       - name: print env
         run: echo "${{ env.PROFILE }}"
