name: notes-app-ci

on:
  push:
    branches:
      - feature-*
      - sandbox
      - dev
      - stage
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  if_merged: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo A PR was merged into the main branch.
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci
      
      # - name: Run Analysis
      #   run: npx eslint --ext .js,.jsx,.ts,.tsx src/
        
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Auto-Applied Code Formatting
      #     branch: ${{github.ref_name}}

      # - name: Run tests
      #   run: npm test

      - name: Run build
        run: npm run build --if-present
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=sivatheja
              -Dsonar.projectKey=check-ci
              -Dsonar.python.coverage.reportPaths=coverage.xml
              -Dsonar.tests=tests/
              -Dsonar.verbose=true

      
