name: print_name
 
on:
    workflow_dispatch:
    push:

jobs:
   android:
     timeout-minutes: 30
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
       - name: Determine env
         id: determine_env
         run: |
            PROFILE=$(echo $GITHUB_REF | cut -d'/' -f3)
            # Check if PROFILE is one of the valid values; otherwise, set it to 'develop'
            if [[ "$PROFILE" = feature_*_fastlane ]]; then
              PROFILE="develop"
            fi
            echo "PROFILE=${PROFILE}" >> $GITHUB_ENV

       - name: Validate env
         id: validate_env
         run: |
           if [[ "${{ env.PROFILE }}" != "develop" && "${{ env.PROFILE }}" != "main" && "${{ env.PROFILE }}" != "stage" && "${{ env.PROFILE }}" != "test" && "${{ env.PROFILE }}" != "feature_*_fastlane" ]]; then
              echo "Invalid PROFILE value: ${{ env.PROFILE }} \n
              branch name shall be either develop/stage/test/main or feature_*_fastlane to trigger the mobile builds"
              exit 1
           fi
 
       - name: print env
         run: echo "${{ env.PROFILE }}"
       - name: check
         run: echo "working"
