name: vercel

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  if_merged: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo A PR was merged into the main branch.

  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x" # Use appropriate Node.js version here

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build --if-present

      - name: Deploy to Dev
        id: deploy-vercel-dev
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Get Vercel Preview URL
        id: get-vercel-preview-url
        uses: ViktorJT/Get-vercel-preview-url@1.2.2
        with:
          vercel_access_token: ${{ secrets.VERCEL_TOKEN }}
          gh_token: ${{ secrets.GIT_TOKEN }}

      - name: Echo preview
        run: echo "Preview url is ready ${{ steps.get-vercel-preview-url.outputs.preview_url }}"
          
      - name: Deploy to Production
        uses: amondnet/vercel-action@v25
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_TL_ENGINE }}
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_ORG_ID }}
